--- # This is my  first YAML playbook for Ansible
- hosts: webservers
  user: ansadmin
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 1.0
  vars_files:
    - conf/copyright.yml
	- conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
	  prompt: Install which package?
  tasks:
    - name: Install {{ pkg_name }} software
	  yum: pkg={{pkg_name}} state=installed
	- name: check for telnet Client
	  yum: pkg=telnet state=absent